---
- name: IP 3 E_Commerce Project
  hosts: all
  remote_user: vagrant
  become: true
  become_user: root

  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true
