---
- name: IP 3 E_Commerce Project
  hosts: all
  remote_user: vagrant
  become: true
  become_user: root

  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Add Docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker - ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install Pip3
      apt:
        name: python3-pip
        state: present

    - name: Install and upgrade pip
      pip:
        name: pip
        extra_args: --upgrade
        executable: pip3

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Installing Git
      apt:
        name: git
        state: present
        update_cache: true

    - name: Cloning the e_commerce repository
      git:
        repo: 'https://github.com/bicosteve/e_commerceIP2'
        dest: /home/code/repo
