---
- name: IP 3 E_Commerce Project
  hosts: all
  remote_user: vagrant
  become: true
  become_user: root

  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true
      tags: aptitude 

    - name: Add Docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install docker - compose 
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/bin/docker-compose
        mode: '755'
      tags: install-compose

    - name: Install Pip3
      apt:
        name: python3-pip
        state: present

    - name: Install and upgrade pip
      pip:
        name: pip
        extra_args: --upgrade
        executable: pip3

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Installing Git
      apt:
        name: git
        state: present
        update_cache: true
      tags: git-install 


    - name: Cloning the e_commerce repository
      git:
        repo: 'https://github.com/bicosteve/e_commerceIP2'
        dest: /home/vagrant/code 
      tags: repo

    - name: Run Docker Compose
      command: docker compose up -d
      args:
        chdir: /home/vagrant/code/e_commerceIP2/
      tags: docker-compose
