---
- name: Cloning the e_commerce repository
  vars:
    git_repo: https://github.com/bicosteve/e_commerceIP2
    destination: /home/vagrant/code/e_commerceIP2
  git:
    repo: '{{ git_repo }}'
    dest: '{{ destination }}'
  tags: clone-repo
