---
- name: Download, Add Docker Repository, and Install Docker-CE
  become: true
  block:
    - name: Download Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags: docker-download

    - name: Add Docker Repository
      become: true
      apt_repository:
        repo: deb deb https://download.docker.com/linux/ubuntu focal stable
        state: present
      tags: docker-repository

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true
      tags: docker-ce 

    - name: Install docker - compose 
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/bin/docker-compose
        mode: '755'
      tags: install-compose
